spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "2.0"
accounts:
  message: "Welcome to EazyBank accounts related local APIs from Production "
  contactDetails:
    name: "John Doe - Developer"
    email: "{cipher}e4bfcc54aa1f0291d8023394df6ddc219259a86c21c146985ee761d234fe98eda77e2766f2e4961b82efbfb88c65b9fb"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
